function navbar(){var e=new Array,r=0;e[0]=0,$(document).scroll(function(){e[++r]=$(document).scrollTop(),e[r]>e[r-1]?$(".navbar").fadeOut():$(".navbar").fadeIn()})}$(document).ready(function(){navbar(),Vue.component("receiver-detail",{data(){return{recevierName:"李* 先生/小姐",recevierPhone:"0912345678",recevierAddress:"******民權東路六段"}},template:`
            <div class='receiverDetail'>
                <div>
                    <p>收件人姓名：<input disabled type="text" :value='recevierName'></p>
                    <p>收件人電話：<input disabled type="text" :value='recevierPhone'></p>
                    <p>收件人地址：<input disabled type="text" :value='recevierAddress'></p>
                </div>
                <p>部分資訊打***以保護個人隱私</p>
                <button  @click='recevierClose'>確認</button>
            </div>
        `,methods:{recevierClose(){$(".receiverDetail").fadeOut(),$(".greyBackground").remove(),$("body").removeClass("stopScroll")}}}),new Vue({el:".memberAll"}),$("#memberId").click(function(){$(".choosenBar2").css("left","0%"),$(this).css("color","#172852"),$(this).siblings().css("color","#cba89a"),$(".memberPart1").fadeIn(700),$(".memberPart1 ~ div").not(".memberPart1").hide()}),$("#memberPsw").click(function(){$(".choosenBar2").css("left","20%"),$(this).css("color","#172852"),$(this).siblings().css("color","#cba89a"),$(".memberPart2").fadeIn(700),$(".memberLine ~ div").not(".memberPart2").hide()}),$("#memberOrder").click(function(){$(".choosenBar2").css("left","40%"),$(this).css("color","#172852"),$(this).siblings().css("color","#cba89a"),$(".memberPart3").fadeIn(700),$(".memberLine ~ div").not(".memberPart3").hide()}),$("#memberRefund").click(function(){$(".choosenBar2").css("left","60%"),$(this).css("color","#172852"),$(this).siblings().css("color","#cba89a"),$(".memberPart4").fadeIn(700),$(".memberLine ~ div").not(".memberPart4").hide()}),$("#memberLike").click(function(){$(".choosenBar2").css("left","80%"),$(this).css("color","#172852"),$(this).siblings().css("color","#cba89a"),$(".memberPart5").fadeIn(700),$(".memberLine ~ div").not(".memberPart5").hide()}),$(".memberOrderDetailAll").hide(),$(".memberOpenDetail").click(function(){console.log("kk"),$(this).parent().parent().next().slideToggle("slow"),$(this).toggleClass("close_detail"),$(this).hasClass("close_detail")?$(this).text("收合明細"):$(this).text("查看明細")}),$(".memberReceiverID").click(function(){recevier=$(this).parent().parent().next().next().next(),recevier.fadeIn(500),$("body").addClass("stopScroll"),$("body").append("<div class='greyBackground'></div>")}),$(".memberLikeHeart").click(function(){let e=this;$(e).attr("src","../images/member/unfavorite.png"),$(e).parent().fadeOut(1e3),setTimeout(function(){$(e).parent().remove()},1e3)})});